# Generated by Django 6.0.3 on 2026-05-29 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('show', 'Pigeon Show'), ('race', 'Race'), ('auction', 'Auction'), ('meetup', 'Enthusiast Meetup'), ('other', 'Other')], default='show', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('district', models.CharField(choices=[('dhaka', 'Dhaka'), ('gazipur', 'Gazipur'), ('narayanganj', 'Narayanganj'), ('tangail', 'Tangail'), ('chittagong', 'Chittagong'), ('cox_bazar', "Cox's Bazar"), ('comilla', 'Comilla'), ('noakhali', 'Noakhali'), ('sylhet', 'Sylhet'), ('moulvibazar', 'Moulvibazar'), ('rajshahi', 'Rajshahi'), ('bogra', 'Bogra'), ('rangpur', 'Rangpur'), ('dinajpur', 'Dinajpur'), ('khulna', 'Khulna'), ('jessore', 'Jessore'), ('barisal', 'Barisal'), ('mymensingh', 'Mymensingh'), ('manikganj', 'Manikganj'), ('other', 'Other')], default='other', max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['date'],
            },
        ),
    ]
