# Generated by Django 6.0.3 on 2026-03-23 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('pigeons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pigeon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='pigeons.pigeon'),
        ),
    ]
