# Generated by Django 6.0.3 on 2026-05-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='pedigree_image',
            field=models.ImageField(blank=True, help_text='Pedigree certificate or family tree photo', null=True, upload_to='auction_pedigree/'),
        ),
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auctions/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='auctions.auction')),
            ],
            options={
                'db_table': 'auction_images',
                'ordering': ['order'],
            },
        ),
    ]
