# Generated by Django 6.0.3 on 2026-06-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam', models.BooleanField(default=False, help_text='Controls whether the camera feature is active in the external app.', verbose_name='Camera enabled')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Remote Config',
                'verbose_name_plural': 'Remote Config',
                'db_table': 'app_remote_config',
            },
        ),
    ]
