# Generated by Django 6.0.3 on 2026-03-23 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedigrees', '0001_initial'),
        ('pigeons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigreerecord',
            name='dam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_of', to='pigeons.pigeon'),
        ),
        migrations.AddField(
            model_name='pedigreerecord',
            name='pigeon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree', to='pigeons.pigeon'),
        ),
        migrations.AddField(
            model_name='pedigreerecord',
            name='sire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sire_of', to='pigeons.pigeon'),
        ),
    ]
