# Generated by Django 6.0.3 on 2026-05-29 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pigeons', '0003_pigeon_pedigree_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('voting_end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contests',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contests/')),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='contests.contest')),
                ('pigeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contest_entries', to='pigeons.pigeon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contest_entries',
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_contest', to='contests.contestentry'),
        ),
        migrations.CreateModel(
            name='ContestVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='contests.contest')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='contests.contestentry')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contest_votes',
                'unique_together': {('contest', 'voter')},
            },
        ),
    ]
