# Generated by Django 6.0.3 on 2026-03-23 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pigeons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pigeon',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigeons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pigeonimage',
            name='pigeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pigeons.pigeon'),
        ),
    ]
