# Generated by Django 6.0.3 on 2026-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeons', '0003_pigeon_pedigree_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigeonimage',
            name='edit_notes',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='pigeonimage',
            name='edit_score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
