# Generated by Django 6.0.3 on 2026-03-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('racing', 'Racing'), ('breeding', 'Breeding'), ('molting', 'Molting'), ('maintenance', 'Maintenance'), ('young', 'Young Pigeons')], max_length=20)),
                ('target_protein', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feed_formulas',
            },
        ),
        migrations.CreateModel(
            name='FeedFormulaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
            ],
            options={
                'db_table': 'feed_formula_items',
            },
        ),
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('cereal', 'Cereal'), ('legume', 'Legume'), ('seed', 'Seed'), ('supplement', 'Supplement')], max_length=20)),
                ('protein_percent', models.FloatField()),
                ('fat_percent', models.FloatField()),
                ('carb_percent', models.FloatField()),
                ('fiber_percent', models.FloatField()),
                ('calories_per_100g', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'grains',
                'ordering': ['name'],
            },
        ),
    ]
