# Generated by Django 6.0.3 on 2026-03-23 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed_generator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedformula',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_formulas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedformulaitem',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feed_generator.feedformula'),
        ),
        migrations.AddField(
            model_name='feedformulaitem',
            name='grain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_generator.grain'),
        ),
    ]
