# Generated by Django 6.0.3 on 2026-05-29 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('like', '❤️ Post Liked'), ('comment', '💬 Comment'), ('follow', '👤 New Follower'), ('offer_received', '💰 Offer Received'), ('offer_accepted', '✅ Offer Accepted'), ('offer_rejected', '❌ Offer Declined'), ('offer_countered', '🔄 Offer Countered'), ('review', '⭐ New Review'), ('message', '✉️ New Message'), ('payment', '💳 Payment Update'), ('contest_winner', '🏆 Contest Winner')], max_length=30)),
                ('message', models.CharField(max_length=300)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
